esphome:
  name: esphome-build-action-example
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'ESPHome Build'
    # password: 'P87dN2YcoPK5'

captive_portal:

binary_sensor:
  - platform: gpio
    id: button
    pin: 0
