name: Build example

on:
  push:
    branches:
      - main

jobs:
  workflows:
    uses: esphome/build-action/.github/workflows/build.yaml@main
    with:
      files: esp32.yml,esp8266.yml
      root_dir: example
      secrets:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
