name: Build

on:
  push:

jobs:
  build:
    name: Build ESPHome binary for ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          # - example/esp32.yml
          - example/esp8266.yml
    steps:
      - uses: actions/checkout@v2
      # - uses: esphome/build@latest
      - uses: ./
        id: esphome-build
        with:
          yaml_file: ${{ matrix.file }}
      - uses: actions/upload-artifact@master
        with:
          name: ${{ steps.esphome-build.outputs.name }}
          path: ${{ steps.esphome-build.outputs.name }}
  deploy:
    name: Deploy new firmware to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          path: example
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - run: tree
      # - run: gem install mustache
      # - run: mkdir -p output
      # - run: ls -al
      # - run: cat site-config.yaml templates/index.mustache | mustache > output.index.html
      # - run: |
      #     jq -s '{"name": "ESPHome", "version": "", "home_assistant_domain": "esphome", "new_install_skip_erase": false, "builds":.}' */manifest.json > output/manifest.json
      # - run: ls -al output/
      # - run: cat output/manifest.json
